# Generated by Django 4.2.26 on 2025-11-13 03:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Redemption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credits_redeemed', models.IntegerField()),
                ('rupees_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redemptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Recognition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credits', models.IntegerField()),
                ('message', models.TextField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('from_student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recognitions_given', to=settings.AUTH_USER_MODEL)),
                ('to_student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recognitions_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CreditBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available_credits', models.IntegerField(default=100)),
                ('monthly_sent', models.IntegerField(default=0)),
                ('last_reset_date', models.DateField(auto_now_add=True)),
                ('total_received', models.IntegerField(default=0)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='credit_balance', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Credit Balances',
            },
        ),
        migrations.CreateModel(
            name='Endorsement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('endorser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='endorsements_given', to=settings.AUTH_USER_MODEL)),
                ('recognition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='endorsements', to='base.recognition')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('recognition', 'endorser')},
            },
        ),
    ]
